In [1]:
import numpy as np
import pandas as pd

from datetime import datetime

In [2]:
myyear = 2015
mymonth = 1
myday = 1
myhour = 2
mymin = 30
mysec = 15

In [3]:
mydate = datetime(myyear, mymonth, myday)

In [4]:
mydate

datetime.datetime(2015, 1, 1, 0, 0)

In [5]:
mydate.year

2015

In [6]:
mydatetime = datetime(myyear, mymonth, myday, myhour, mymin, mysec)

In [7]:
mydatetime

datetime.datetime(2015, 1, 1, 2, 30, 15)

In [9]:
mydatetime.second

15

In [10]:
myser = pd.Series(['Nov 3, 1990', '2000-01-01', None])

In [11]:
myser

0    Nov 3, 1990
1     2000-01-01
2           None
dtype: object

In [12]:
myser[0]

'Nov 3, 1990'

In [15]:
# We can convert this string to a date object
timeser = pd.to_datetime(myser, format='mixed')

In [16]:
timeser[0].year

1990

In [17]:
sales = pd.read_csv('RetailSales_BeerWineLiquor.csv')

In [18]:
sales

           DATE  MRTSSM4453USN
0    1992-01-01           1509
1    1992-02-01           1541
2    1992-03-01           1597
3    1992-04-01           1675
4    1992-05-01           1822
..          ...            ...
335  2019-12-01           6630
336  2020-01-01           4388
337  2020-02-01           4533
338  2020-03-01           5562
339  2020-04-01           5207

[340 rows x 2 columns]

In [19]:
sales['DATE']

0      1992-01-01
1      1992-02-01
2      1992-03-01
3      1992-04-01
4      1992-05-01
          ...
335    2019-12-01
336    2020-01-01
337    2020-02-01
338    2020-03-01
339    2020-04-01
Name: DATE, Length: 340, dtype: object

In [21]:
sales['DATE'] = pd.to_datetime(sales['DATE'])

In [22]:
sales

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [23]:
sales['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [24]:
# We can parse in the dates instead of taking the manual route of to_datetime
sales = pd.read_csv('RetailSales_BeerWineLiquor.csv', parse_dates=[0])

In [25]:
sales['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

##### Resampling/Grouping (when the time series has the time as the index)

In [26]:
sales = sales.set_index('DATE')

In [29]:
# Grouping by the year
sales.resample(rule='YE').mean()

            MRTSSM4453USN
DATE
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000